// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://plhxeyfwxndafsxhmqnd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBsaHhleWZ3eG5kYWZzeGhtcW5kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxMDA0MDUsImV4cCI6MjA2MzY3NjQwNX0.K5fRvPPRA2zW44U3Cf2HAjNh4QgmzcKC28xL1THAB0c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);